### ISSUE TITLE
http.post function not working with api

### ISSUE THREAD

**Issue by arslan-mumtaz** [vmanchev/ionic3-seed-jwt#1]
**Hi there,i was just using your app for my project and  just replace the api in the config file and added my function. Giving me No access control allow origin error. Can you please help what i am doing wrong. THanks**

login(credentials: CredentialsModel) {
    let headers = new Headers ({ 'Content-Type': 'application/x-www-form-urlencoded; charset=UTF-8' });
    let options = new RequestOptions({ headers: headers, method: "post" });
    
       return this.http.post(this.cfg.apiUrl+'user/login',credentials,options)
       .map(res => res.json()).subscribe(res => {
        let alert = this.alertCtrl.create({
          title: 'Response message',
          subTitle: res.message,
          buttons: ['Dismiss']
        });
        alert.present();

        //this.userData.login(res.data.username);
    //  this.navCtrl.push(ProfilePage);
      }, (err) => {
      alert("failed");
    });
}

**Comment by vmanchev** [comment]
This error is caused by the backend api you are using. Depends on the platform you have there (Linux & Apache, etc) you may need to find out how to enable CORS on the backend side.

**Comment by arslan-mumtaz** [comment]
Okay i will try to enable the CORS form the backend, but the same function did work for me when i am using doing it with ionic2 and angular 2..
